

//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by tool.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
#pragma warning disable 1573

using System.Data.Entity;
using Pebb.Infrastructure.Data;

namespace Pebb.Modules.DigitalAccounts.Data
{	
    public interface IDigitalAccountsDatabaseFactory : IDatabaseFactory { }
	#region Data Context
	public partial class DigitalAccountsDatabaseFactory : DbContext
	{	



	}
	#endregion
}
